stack: stack.c push.o pop.o display.o hello.o
	cc -o stack stack.c push.o pop.o display.o hello.o

push.o: push.c
	cc -c push.c

pop.o: pop.c
	cc -c pop.c

display.o: display.c
	cc -c display.c

hello.o: hello.c
	cc -c hello.c

